[theme]
primaryColor = "#D71934"
backgroundColor = "#F2ECE1"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3D0C11"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
